#!/usr/bin/julia
push!(LOAD_PATH, dirname(@__FILE__))
push!(LOAD_PATH, "/usr/share/julia/DistroHelper")

using DistroHelper
using Pkg

function main(argv)
	if length(argv) == 0
		exit(0)
	elseif argv[1] in ("slug", "depends")  # raw print
		print(getfield(DistroHelper, Symbol(argv[1]))(argv[2:end]...))
	elseif argv[1] in ("gather_stdlib_manifest", "distro_manifest_")  # requires pretty print
		result = getfield(DistroHelper, Symbol(argv[1]))(argv[2:end]...)
		Pkg.TOML.print(result)
	elseif argv[1] in ("distro_project", "distro_manifest", "distro_merge", "metadata", "download")  # no print
		getfield(DistroHelper, Symbol(argv[1]))(argv[2:end]...)
	else
		throw(Base.error("unsupported args"))
	end
end

main(ARGS)
